---
- name: install apache
  hosts: webservers

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Configure Apache
      template:
        src: templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      notify:
        - restart apache

    - name: enable apache
      service:
        name: httpd
        state: started
        enabled: true

  post_tasks:
    - name: check http access
      uri:
        url: "http://{{ ansible_hostname }}:8080"

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
